import type { CategoryExpertPackV1 } from "../types";

/**
 * Voice, VoIP, and UCaaS billing pack.
 *
 * This is intentionally separate from fixed-line broadband: a Nextiva,
 * RingCentral, or hosted-PBX invoice can contain seats, minutes, recordings,
 * E911, USF, and telecom taxes even when no circuit or bandwidth is billed.
 */
export const voiceUcaasPack: CategoryExpertPackV1 = {
  schemaVersion: "category-expert-pack-v1",
  categoryKey: "voice-ucaas",
  displayName: "Voice, VoIP & UCaaS",
  parentKey: "telecom-connectivity",
  version: "2026.08.2",
  status: "draft",
  jurisdictions: ["US"],
  effectiveFrom: "2026-01-01",
  effectiveTo: null,
  defaultFreshnessDays: 30,

  scope: {
    includes: [
      "Hosted PBX and business VoIP",
      "Unified communications as a service (UCaaS)",
      "SIP trunking and business voice seats",
      "Usage minutes, call recording, analytics, and add-on packages",
      "Voice-related E911, USF, FCC, and telecom tax lines",
    ],
    excludes: [
      "Fixed-line broadband or DIA circuits",
      "Wireless mobile voice and data plans",
      "Consumer phone service",
      "Hardware purchases unless separately identified as a one-time charge",
    ],
    adjacentCategories: ["business-broadband-dia", "wireless-mobility", "saas-subscriptions"],
  },

  documentTypes: [
    {
      type: "voice_ucaas_invoice",
      indicators: [
        "VoIP",
        "UCaaS",
        "Hosted PBX",
        "Office Enterprise",
        "Minutes Usage",
        "FUSF",
        "E911",
        "Call Recording",
      ],
      requiredFields: ["account_number", "billing_period", "plan_or_service", "total_charges"],
    },
  ],

  billAnatomy: {
    identityFields: ["account_number", "phone_number", "extension", "service_address", "tenant_or_site_id"],
    periodFields: ["billing_period_start", "billing_period_end", "activation_date", "cancellation_date"],
    quantityFields: ["active_lines", "seats", "minutes", "recording_storage", "fax_lines"],
    pricingFields: ["plan_fee", "line_fee", "minute_rate", "add_on_fee", "device_or_endpoint_fee"],
    taxFeeFields: [
      "federal_universal_service_fund",
      "fcc_regulatory_fee",
      "e911_fee",
      "state_local_telecom_tax",
      "regulatory_recovery_fee",
    ],
    contractFields: ["term_months", "renewal_date", "notice_period_days", "early_termination_fee"],
  },

  lineItems: [
    {
      canonicalCode: "VOICE-PLAN-01",
      label: "Voice Plan / Seat Subscription",
      aliases: ["Local Subscription Plan Fee", "Office Enterprise", "Hosted PBX", "Voice Plan", "Seat Subscription"],
      meaning: "Recurring plan or seat charge for hosted business voice service. Validate the billed seats against the active-user or phone inventory.",
      chargeClass: "fixed",
      units: ["seats", "lines", "flat"],
      calculation: "active_seats * contracted_seat_rate",
      expectedContext: ["voice_ucaas_invoice"],
      benchmarkable: true,
      regulatory: false,
      commonContractTreatment: ["monthly_recurring", "annual_commitment"],
      anomalyRules: ["check_active_seats_against_identity_or_phone_inventory", "check_plan_tier_against_contract"],
    },
    {
      canonicalCode: "VOICE-USAGE-01",
      label: "Voice Minutes / Usage",
      aliases: ["Minutes Usage Charge", "Usage Minutes", "Call Usage", "Outbound Minutes", "Inbound Minutes"],
      meaning: "Variable usage charge based on billed call minutes or another explicitly stated voice usage unit.",
      chargeClass: "usage",
      units: ["minutes"],
      calculation: "billed_minutes * contracted_minute_rate",
      expectedContext: ["metered_voice_service"],
      benchmarkable: true,
      regulatory: false,
      commonContractTreatment: ["included_allowance", "overage_rate", "unlimited_plan"],
      anomalyRules: ["check_usage_against_included_allowance", "check_rate_against_contract"],
    },
    {
      canonicalCode: "VOICE-LINE-01",
      label: "Additional Voice Line",
      aliases: ["Additional Enterprise Line", "Additional Line", "Phone Line", "Extension"],
      meaning: "Additional phone number, seat, or extension billed beyond the base plan.",
      chargeClass: "fixed",
      units: ["lines", "seats"],
      expectedContext: ["voice_ucaas_invoice"],
      benchmarkable: true,
      regulatory: false,
      commonContractTreatment: ["monthly_recurring", "prorated_addition"],
      anomalyRules: ["check_line_count_against_inventory", "check_proration_period"],
    },
    {
      canonicalCode: "VOICE-ADDON-01",
      label: "Voice Feature or Add-on",
      aliases: ["Analytics Base Package", "Analytics User", "Advanced Call Recordings", "Call Recording", "Auto Attendant", "Fax"],
      meaning: "Optional feature, analytics, recording, fax, contact-center, or endpoint add-on attached to a voice subscription.",
      chargeClass: "fixed",
      units: ["users", "lines", "flat"],
      expectedContext: ["voice_ucaas_invoice", "contact_center_invoice"],
      benchmarkable: false,
      regulatory: false,
      commonContractTreatment: ["monthly_recurring", "add_on_order"],
      anomalyRules: ["check_add_on_assignment_and_active_user_count"],
    },
    {
      canonicalCode: "VOICE-USF-01",
      label: "Federal Universal Service Fund (VoIP) Surcharge",
      aliases: ["Federal FUSF (VoIP)", "FUSF", "VoIP Universal Service", "Federal USF"],
      meaning: "Provider-billed contribution-related surcharge. The rate and assessable base require the invoice period, service scope, and current official contribution-factor source.",
      chargeClass: "assessment",
      units: ["percentage", "flat"],
      expectedContext: ["interstate_voice_service"],
      benchmarkable: false,
      regulatory: true,
      commonContractTreatment: ["pass_through_at_cost"],
      anomalyRules: ["verify_federal_contribution_factor_and_assessable_base"],
    },
    {
      canonicalCode: "VOICE-E911-01",
      label: "E911 / Emergency Service Fee",
      aliases: ["State E-911", "E911 Service Fee", "911 Fee", "Emergency Service Fee"],
      meaning: "State or local emergency communications charge. Treatment depends on jurisdiction, line count, and the service address shown on the source.",
      chargeClass: "assessment",
      units: ["flat_per_line", "flat_per_location", "flat"],
      expectedContext: ["voice_capable_service"],
      benchmarkable: false,
      regulatory: true,
      commonContractTreatment: ["pass_through_at_cost"],
      anomalyRules: ["check_e911_line_or_location_basis"],
    },
    {
      canonicalCode: "VOICE-FCC-01",
      label: "FCC / Regulatory Recovery Fee",
      aliases: ["Federal FCC Regulatory Fee (VoIP)", "Regulatory Recovery Fee", "FCC Fee", "Regulatory Fee"],
      meaning: "Provider-imposed regulatory recovery or FCC-related line that must remain distinct from a government tax unless the source explicitly says otherwise.",
      chargeClass: "surcharge",
      units: ["percentage", "flat"],
      expectedContext: ["voice_ucaas_invoice"],
      benchmarkable: false,
      regulatory: true,
      commonContractTreatment: ["pass_through_or_carrier_imposed"],
      anomalyRules: ["check_fee_definition_and_contract_pass_through_right"],
    },
    {
      canonicalCode: "VOICE-TAX-01",
      label: "Telecommunications Sales Tax",
      aliases: ["Local/County/State Telecommunications Sales Tax", "Telecommunications Tax", "State Telecom Tax", "Telecom Sales Tax"],
      meaning: "Jurisdiction-specific tax on communications service. Determine tax treatment from the service location and exemption status, not from the vendor name alone.",
      chargeClass: "tax",
      units: ["percentage", "flat"],
      expectedContext: ["taxable_voice_service"],
      benchmarkable: false,
      regulatory: true,
      commonContractTreatment: ["pass_through_at_cost"],
      anomalyRules: ["check_tax_jurisdiction_and_exemption"],
    },
    {
      canonicalCode: "VOICE-ONE-TIME-01",
      label: "One-Time Voice Service Charge",
      aliases: ["Activation Charge", "Restoral Charge", "Setup Fee", "Porting Fee", "Installation Charge"],
      meaning: "Non-recurring charge for activation, restoration, porting, or implementation. Confirm it is not being billed repeatedly.",
      chargeClass: "one_time",
      units: ["flat"],
      expectedContext: ["new_service_order", "service_restoration", "number_port"],
      benchmarkable: false,
      regulatory: false,
      commonContractTreatment: ["waived_on_term_contract", "charged_on_event"],
      anomalyRules: ["check_one_time_charge_is_not_recurring"],
    },
    {
      canonicalCode: "VOICE-LATE-01",
      label: "Late Payment Charge",
      aliases: ["Late Payment", "Late Fee", "Finance Charge"],
      meaning: "Charge related to payment timing or finance terms; do not classify it as a service price or recurring voice rate.",
      chargeClass: "penalty",
      units: ["flat", "percentage"],
      expectedContext: ["past_due_account"],
      benchmarkable: false,
      regulatory: false,
      commonContractTreatment: ["late_payment_terms"],
      anomalyRules: ["check_payment_history_and_contract_terms"],
    },
  ],

  pricingModels: [
    {
      key: "ucaas_seat_plus_usage",
      explanation: "Recurring plan or seat charges plus explicitly measured minutes, feature add-ons, regulatory recoveries, and applicable taxes.",
      fixedComponents: ["plan_fee", "line_fee", "feature_add_ons"],
      variableComponents: ["minutes_usage"],
      passThroughComponents: ["fusf", "e911", "telecom_taxes"],
      formulas: ["total = recurring_voice + usage + fees + taxes - credits"],
      requiredDimensions: ["active_line_or_seat_count", "plan_name", "billing_period", "service_location"],
    },
  ],

  billQuality: {
    goodSignals: [
      {
        ruleId: "voice-account-period-present",
        description: "Account identifier and billing period are visible, with recurring service separated from usage and taxes.",
        severity: "info",
        deterministic: true,
        requiredFields: ["account_number", "billing_period", "plan_or_service"],
        evidenceRequired: true,
        currentResearchRequired: false,
      },
    ],
    anomalyRules: [
      {
        ruleId: "voice-lines-vs-inventory",
        description: "Billed voice lines or seats differ from the customer's active-user, phone, or endpoint inventory.",
        severity: "medium",
        deterministic: true,
        requiredFields: ["active_lines", "phone_inventory"],
        evidenceRequired: true,
        currentResearchRequired: false,
      },
      {
        ruleId: "voice-usage-vs-allowance",
        description: "Measured minutes exceed an explicitly extracted included allowance or appear without a stated usage basis.",
        severity: "medium",
        deterministic: true,
        requiredFields: ["minutes", "included_allowance"],
        evidenceRequired: true,
        currentResearchRequired: false,
      },
      {
        ruleId: "voice-fee-definition",
        description: "Regulatory recovery, FUSF, or E911 lines lack a source-backed definition or jurisdictional basis.",
        severity: "high",
        deterministic: false,
        requiredFields: ["fee_line", "service_location", "billing_period"],
        evidenceRequired: true,
        currentResearchRequired: true,
      },
      {
        ruleId: "voice-recurring-proration",
        description: "A recurring line changes mid-period without an extracted service interval or proration explanation.",
        severity: "medium",
        deterministic: true,
        requiredFields: ["line_service_period", "billing_period"],
        evidenceRequired: true,
        currentResearchRequired: false,
      },
    ],
    contractChecks: [
      {
        ruleId: "voice-plan-vs-contract",
        description: "Plan tier, line count, usage allowance, and renewal terms should be compared to the governing order or contract.",
        severity: "high",
        deterministic: false,
        requiredFields: ["plan_name", "active_lines", "contract_term"],
        evidenceRequired: true,
        currentResearchRequired: false,
      },
    ],
    arithmeticChecks: [
      {
        ruleId: "voice-components-to-total",
        description: "Recurring lines plus usage plus fees and taxes less credits reconcile to the source total when all components are present.",
        severity: "high",
        deterministic: true,
        requiredFields: ["recurring_charges", "usage_charges", "fees", "taxes", "credits", "invoice_total"],
        evidenceRequired: true,
        currentResearchRequired: false,
      },
    ],
  },

  benchmarkPolicy: {
    supportedMetrics: ["effective_price_per_active_voice_line", "effective_price_per_included_minute"],
    requiredDimensions: ["provider", "plan_name", "active_line_count", "billing_period", "service_scope"],
    minimumComparableCount: 5,
    sourceRequirements: ["Customer contract or order form", "Official provider plan and fee documentation", "USAC contribution factors where applicable"],
    quoteRequiredWhen: ["custom_enterprise_voice_plan", "current_regulatory_fee", "any_market_price_or_savings_claim"],
    prohibitedClaims: [
      "Treating a provider recovery fee as a government tax without source evidence.",
      "Comparing a custom UCaaS plan to a consumer or unrelated business voice plan.",
      "Claiming savings from line removal without an authorized active-user or phone inventory review.",
    ],
  },

  optimizationLevers: [
    {
      key: "inactive_voice_line_review",
      description: "Compare billed phone numbers, extensions, and seats with an authorized active-user or endpoint inventory.",
      prerequisites: ["authorized_phone_or_identity_inventory"],
      risks: ["service_or_emergency_calling_interruption"],
      needsAuthorization: true,
    },
    {
      key: "voice_plan_and_add_on_review",
      description: "Review plan tier, minutes, recordings, analytics, fax, and contact-center add-ons against actual use and contract terms.",
      prerequisites: ["contract_or_order_form", "usage_or_feature_inventory"],
      risks: ["feature_removal", "renewal_or_termination_consequence"],
      needsAuthorization: true,
    },
  ],

  currentResearchPolicy: {
    mandatoryTriggers: ["current_usf_factor", "current_state_e911_fee", "current_tax_question", "current_provider_plan_price"],
    preferredSources: [
      "https://www.usac.org/service-providers/making-payments/contribution-factors/",
      "https://www.fcc.gov/general/911-services",
      "https://www.nextiva.com/",
    ],
    allowedDomains: ["usac.org", "fcc.gov", "nextiva.com", "ringcentral.com", "8x8.com"],
    freshnessDays: 30,
    cacheKeyDimensions: ["provider", "plan_name", "jurisdiction", "billing_period"],
  },

  outputPolicy: {
    requiredCaveats: [
      "Voice fees, E911, USF, and telecom taxes depend on service scope, jurisdiction, line basis, and billing period.",
      "A line-count or plan finding requires an authorized inventory or contract comparison; invoice text alone does not prove waste.",
    ],
    confidenceThresholds: { extraction: 0.92, classification: 0.9 },
    humanReviewTriggers: ["voice_line_removal", "regulatory_fee_question", "material_finding_from_draft_pack"],
  },

  evalCaseIds: [
    "eval-voice-ucaas-001",
    "eval-voice-ucaas-002",
    "eval-voice-ucaas-003",
    "eval-voice-ucaas-004",
    "eval-voice-ucaas-005",
    "eval-voice-ucaas-006",
    "eval-voice-ucaas-007",
    "eval-voice-ucaas-008",
    "eval-voice-ucaas-009",
    "eval-voice-ucaas-010",
  ],
};
